on: [push]

jobs:
  testing_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: Test action step
        id: test
        uses: ofrank123/clean-releases-action@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
